package extractor_test

import (
	"context"
	"fmt"
	"testing"

	"github.com/goto/salt/log"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"

	"github.com/goto/optimus/core/job"
	"github.com/goto/optimus/ext/extractor"
	"github.com/goto/optimus/ext/store/bigquery"
)

func TestDefaultExtractorFunc(t *testing.T) {
	ctx := context.Background()
	l := log.NewNoop()

	t.Run("should return error if client is nil", func(t *testing.T) {
		extractorFunc := extractor.DefaultExtractorFunc(nil)
		urnToDDL, err := extractorFunc(nil, nil, nil)
		assert.Error(t, err)
		assert.Nil(t, urnToDDL)
	})
	t.Run("should return no error if get ddl is fail", func(t *testing.T) {
		resourceURNs := []job.ResourceURN{"bigquery://project:dataset.name"}

		client := new(Client)
		defer client.AssertExpectations(t)

		client.On("BulkGetDDLView", ctx, mock.Anything, mock.Anything).Return(nil, fmt.Errorf("some error"))
		extractorFunc := extractor.DefaultExtractorFunc(client)
		urnToDDL, err := extractorFunc(ctx, l, resourceURNs)
		assert.NoError(t, err)
		assert.Empty(t, urnToDDL)
	})
	t.Run("should return ddl given corresponding resourceURN", func(t *testing.T) {
		resourceURNs := []job.ResourceURN{
			"bigquery://project:dataset.table",
			"bigquery://project:dataset.view",
		}

		client := new(Client)
		defer client.AssertExpectations(t)

		client.On("BulkGetDDLView", ctx, mock.Anything, mock.Anything).Return(map[job.ResourceURN]string{
			"bigquery://project:dataset.table": "",
			"bigquery://project:dataset.view":  "select * from anotherproject.dataset.anothertable",
		}, nil)
		extractorFunc := extractor.DefaultExtractorFunc(client)
		urnToDDL, err := extractorFunc(ctx, l, resourceURNs)
		assert.NoError(t, err)
		assert.Len(t, urnToDDL, 2)
	})
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// BulkGetDDLView provides a mock function with given fields: ctx, dataset, names
func (_m *Client) BulkGetDDLView(ctx context.Context, dataset bigquery.Dataset, names []string) (map[job.ResourceURN]string, error) {
	ret := _m.Called(ctx, dataset, names)

	var r0 map[job.ResourceURN]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bigquery.Dataset, []string) (map[job.ResourceURN]string, error)); ok {
		return rf(ctx, dataset, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bigquery.Dataset, []string) map[job.ResourceURN]string); ok {
		r0 = rf(ctx, dataset, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[job.ResourceURN]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bigquery.Dataset, []string) error); ok {
		r1 = rf(ctx, dataset, names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *Client) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DatasetHandleFrom provides a mock function with given fields: dataset
func (_m *Client) DatasetHandleFrom(dataset bigquery.Dataset) bigquery.ResourceHandle {
	ret := _m.Called(dataset)

	var r0 bigquery.ResourceHandle
	if rf, ok := ret.Get(0).(func(bigquery.Dataset) bigquery.ResourceHandle); ok {
		r0 = rf(dataset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bigquery.ResourceHandle)
		}
	}

	return r0
}

// ExternalTableHandleFrom provides a mock function with given fields: dataset, name
func (_m *Client) ExternalTableHandleFrom(dataset bigquery.Dataset, name string) bigquery.ResourceHandle {
	ret := _m.Called(dataset, name)

	var r0 bigquery.ResourceHandle
	if rf, ok := ret.Get(0).(func(bigquery.Dataset, string) bigquery.ResourceHandle); ok {
		r0 = rf(dataset, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bigquery.ResourceHandle)
		}
	}

	return r0
}

// TableHandleFrom provides a mock function with given fields: dataset, name
func (_m *Client) TableHandleFrom(dataset bigquery.Dataset, name string) bigquery.TableResourceHandle {
	ret := _m.Called(dataset, name)

	var r0 bigquery.TableResourceHandle
	if rf, ok := ret.Get(0).(func(bigquery.Dataset, string) bigquery.TableResourceHandle); ok {
		r0 = rf(dataset, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bigquery.TableResourceHandle)
		}
	}

	return r0
}

// ViewHandleFrom provides a mock function with given fields: dataset, name
func (_m *Client) ViewHandleFrom(dataset bigquery.Dataset, name string) bigquery.ResourceHandle {
	ret := _m.Called(dataset, name)

	var r0 bigquery.ResourceHandle
	if rf, ok := ret.Get(0).(func(bigquery.Dataset, string) bigquery.ResourceHandle); ok {
		r0 = rf(dataset, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bigquery.ResourceHandle)
		}
	}

	return r0
}
