version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errname
    - errorlint
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - zerologlint
  settings:
    goconst:
      numbers: true
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
      enabled-tags:
        - diagnostic
    gosec:
      excludes:
        - G101
        - G115
    revive:
      severity: error
      rules:
        - name: atomic
        - name: context-as-argument
        - name: defer
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: early-return
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: modifies-parameter
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: unexported-naming
        - name: var-naming
        - name: unused-receiver
        - name: unused-parameter
        - name: useless-break
        - name: unnecessary-stmt
        - name: unreachable-code
    staticcheck:
      checks:
        - all
        - -S1002
        - -SA1019
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - contextcheck
          - gocritic
        path: _test\.go
      - linters:
          - gocritic
          - testpackage
          - unparam
        path: tests
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - api/proto
      - api/third_party
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/goto/optimus)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/goto/optimus
  exclusions:
    generated: lax
    paths:
      - api/proto
      - api/third_party
      - third_party$
      - builtin$
      - examples$
