run:
  timeout: 5m
  go: "1.20"
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - sloglint
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - zerologlint
linters-settings:
  gofumpt:
    extra-rules: true
  revive:
    severity: error
    rules:
      - name: atomic
      - name: context-as-argument
      - name: defer
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: early-return
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-parameter
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: unexported-naming
      - name: var-naming
      - name: unused-receiver
      - name: unused-parameter
      - name: useless-break
      - name: unnecessary-stmt
      - name: unreachable-code
  goconst:
    ignore-tests: true
    numbers: true
  gomnd:
    ignored-numbers: # Why we have a big range of file permissions
      - '0o600'
      - '0o644'
      - '0o655'
      - '0o666'
      - '0o770'
      - '0o755'
      - '0o765'
      - '0o777'
    ignored-functions:
      - 'survey.MinLength'
      - 'survey.MaxLength'
      - 'args.Error'
  gosec:
    excludes:
      - G101
  gosimple:
    checks:
      - "all"
      - "-S1002"
  staticcheck:
    checks:
      - "all"
      - "-SA1019"
  goimports:
    local-prefixes: github.com/goto/optimus
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/goto/optimus) # Groups all imports with the specified Prefix.
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
    enabled-tags:
      - diagnostic
  unparam:
    # Inspect exported functions.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    check-exported: true
issues:
  exclude-dirs:
    - api/proto
    - api/third_party
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocritic
        - contextcheck
    - path: tests
      linters:
        - gocritic
        - gomnd
        - unparam
        - testpackage
severity:
  default-severity: error