{
 "title": "Optimus Job Monitoring  End User ( Interactive )",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "postgres" },
   { "name": "project", "query": "select name from project;" },
   {
    "name": "namespace",
    "query": "select name from namespace where project_name in ($project)"
   },
   {
    "name": "label",
    "query": "SELECT distinct(stuff.value) result  FROM job, jsonb_each(job.labels) stuff where project_name in ($project) and namespace_name in ($namespace);"
   },
   {
    "name": "job",
    "query": "select name from job where project_name in ($project) and namespace_name in ($namespace)"
   },
   {
    "name": "schedule_time",
    "query": "select TO_CHAR(scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS')  from job_run where job_name='$job' and   $__timeFilter(scheduled_at) order by scheduled_at "
   }
  ]
 },
 "panels": [
  {
   "title": "Panels Specific To   \"$job\" ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$job \"$schedule_time\" Job Timeline Gant",
   "type": "marcusolsson-gantt-panel",
   "description": "This panel also has airflow link to the job in the tooltip.\nClick on an operator to get the Airflow Link",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select \n      opr.type , \n      opr.name, \n      opr.status,\n      extract( epoch from opr.start_time)*1000 as start, \n      extract( epoch from case when opr.end_time > now() then now() else opr.end_time end)  *1000 as end,\n      opr.start_time  , opr.end_time \n      from (\n  select *, 'sensor' as type from sensor_run \n  union all \n  select *, 'task' as type from task_run \n  union all \n  select *, 'hook' as type  from hook_run \n) as opr join job_run as jr \non opr.job_run_id = jr.id \nwhere jr.scheduled_at = to_timestamp('$schedule_time', 'DAY DD/mm/yyyy HH24:MI:SS') and jr.job_name = '$job' \n\nunion \nselect 'delay' as type, \n      'schedule_delay' as name, \n      'schedule_delay' as status,\n      extract( epoch from scheduled_at)*1000 as start, \n      extract( epoch from start_time)  *1000 as end,\n      scheduled_at as start_time  , start_time as end_time \nfrom job_run \nwhere scheduled_at = to_timestamp('$schedule_time', 'DAY DD/mm/yyyy HH24:MI:SS') and job_name = '$job'\n"
    }
   ]
  },
  {
   "title": "Job MetaData",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  window_spec ->>'WindowSize' as WindowSize , schedule->'Interval' as Schedule, owner, labels \nFROM\n  job\nWHERE name = '$job'\n"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "table",
   "description": "Shows all upstreams of the selected job in project. Adhered filter:\n* project\n* job",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "with job_schedule_cte as (\n    select\n        id,\n        project_name,\n        name,\n        schedule::json -> 'Interval' as schedule_cron\n    from job\n),\njob_upstream_cte as (\n    select\n        job_id,\n        upstream_job_id as upstream_id,\n        upstream_job_name as upstream_name,\n        case\n            when upstream_external then 'external'\n            when not upstream_external then 'internal'\n        end as _type,\n        upstream_type as deduction_strategy\n    from job_upstream\n    where\n        project_name in ($project) and\n        job_name = '$job' and\n        upstream_job_name != ''\n)\n\nselect\n    js.project_name as project,\n    ju.upstream_name as upstream,\n    js.schedule_cron as schedule,\n    ju.deduction_strategy as strategy,\n    ju._type as type \nfrom job_schedule_cte js\njoin job_upstream_cte ju\n    on js.id = ju.job_id;"
    }
   ]
  },
  {
   "title": "Downstream",
   "type": "table",
   "description": "Something something",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "with job_schedule_cte as (\n    select\n        id,\n        project_name,\n        name,\n        schedule::json -> 'Interval' as schedule_cron, \n        labels\n    from job\n),\njob_upstream_cte as (\n    select\n        job_id,\n        upstream_type as deduction_strategy\n    from job_upstream\n    where\n        upstream_project_name in ($project) and\n        upstream_job_name = '$job'\n)\n\nselect\n    js.project_name as project,\n    js.name as downstream,\n    js.labels,\n    js.schedule_cron as schedule,\n    ju.deduction_strategy as strategy\nfrom job_schedule_cte js\njoin job_upstream_cte ju\n    on js.id = ju.job_id;"
    }
   ]
  },
  {
   "title": "Aggregate Operator Run Duration",
   "type": "timeseries",
   "description": "Shows the break down of job run based on duration of each operator. This panel adheres to filters:\n* project\n* job",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "select\n  jr.job_name,\n  jr.scheduled_at,\n  EXTRACT( epoch from jr.start_time - jr.scheduled_at) as schedule_delay,\n  extract( epoch from case when now() < max(sr.end_time) then now() else max(sr.end_time) end - min(sr.start_time)) as upstream_wait_duration,\n  extract( epoch from case when now() < max(tr.end_time) then now() else max(tr.end_time) end - min(tr.start_time)) as task_duration,\n  extract( epoch from case when now() < max(hr.end_time) then now() else max(hr.end_time) end - min(hr.start_time)) as hook_duration,\n  case when now() < max(sr.end_time) then true else false end is_sensor_stil_running,\n  case when now() < max(tr.end_time) then true else false end is_task_stil_running,\n  case when now() < max(hr.end_time) then true else false end is_hook_stil_running\nfrom\n  job_run jr\n  left join sensor_run sr on jr.id = sr.job_run_id\n  left join task_run tr on jr.id = tr.job_run_id\n  left join hook_run hr on jr.id = hr.job_run_id\nwhere\n  $__timeFilter(jr.scheduled_at)\n  and job_name = '$job'\ngroup by \n  jr.job_name, \n  jr.scheduled_at, \n  jr.start_time \norder by \n  jr.scheduled_at\n"
    }
   ]
  },
  {
   "title": "Job Duration Pattern",
   "type": "barchart",
   "description": "Shows the pattern of job run duration based on the scheduled time. Adhered filters:\n* project\n* job",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT scheduled_at, \n        start_time,\n        status, \n        sla_alert as sla_breached,\n        TO_CHAR(scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS') as schedule_time,\n        EXTRACT(epoch from case when status = 'running' then now() - start_time  else end_time - start_time end) as duration\nFROM \n  job_run\nWHERE \n  $__timeFilter(scheduled_at) \n  and \n  project_name in ($project) \n  and \n  namespace_name in ($namespace)\n  and \n  job_name = '$job'\norder by scheduled_at\nlimit 100\n"
    }
   ]
  },
  {
   "title": "Job Run State",
   "type": "status-history",
   "description": "Shows the job statuses for each scheduled time in relation to its SLA. The filters it adheres to are:\n* project\n* job",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT scheduled_at, \n        case when sla_definition = 0 then float8 'Infinity' else sla_definition end as user_defined_sla, \n        sla_alert as sla,\n        status as job_state\nFROM \n  job_run\nWHERE \n  $__timeFilter(scheduled_at) \n  and \n  project_name in ($project) \n  and \n  namespace_name in ($namespace)\n  and \n  job_name = '$job'\norder by scheduled_at\nlimit 60\n"
    }
   ]
  },
  { "title": "Grouped", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "worst health jobs (failure percentage)",
   "type": "barchart",
   "description": "percentage failure in the selected time window",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\nSELECT  jr.job_name, \n        100 * sum(case when status = 'failed' then 1 else 0 end ) / count(*) failure_percentage,\n        sum(case when status = 'failed' then 1 else 0 end )  failure_count,\n        sum(case when status = 'success' then 1 else 0 end )  success_count,\n        count(*) total_runs_count\nFROM \n  job_run jr\njoin job_labels jl\non\n  jr.project_name = jl.project_name and\n  jr.job_name = jl.job_name\nWHERE \n  $__timeFilter(jr.scheduled_at) \n  and \n  jr.project_name in ($project) \n  and \n  jr.namespace_name in ($namespace)\n  and\n  jl.job_label in ($label)\nGROUP BY jr.job_name\nhaving 100 * sum(case when status = 'failed' then 1 else 0 end ) / count(*) > 0\nORDER BY failure_percentage desc \nlimit 20\n"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "table",
   "description": "Shows the number of resources in use. Adhered filters:\n* project\n* namespace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "with job_sources as (\n    select\n        name as job_name,\n        unnest(sources) as resource_name\n    from job\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n),\nsplit_job_sources as (\n    select job_name, string_to_array(resource_name, '//') as split_resource_name\n    from job_sources\n),\ncleaned_job_sources as (\n    select job_name, replace(split_resource_name[2], ':', '.') as resource_name\n    from split_job_sources\n)\n\nselect\n    resource_name, count(job_name) as job_downstream\nfrom cleaned_job_sources\ngroup by resource_name\norder by job_downstream desc;\n"
    }
   ]
  },
  {
   "title": "Static Unresolved Upstreams",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\nSELECT\n  ju.project_name , ju.job_name,  ju.upstream_resource_urn\n\nFROM\n  job_upstream ju\njoin job_labels jl\non\n  ju.project_name = jl.project_name and\n  ju.job_name = jl.job_name\nWhere \n  ju.upstream_state = 'unresolved' \n  and ju.upstream_type = 'static'\n  and ju.project_name in ($project)\n  and jl.job_label in ($label)"
    }
   ]
  },
  {
   "title": "top 10 longest still running jobs ",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        job.owner as owner,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\nSELECT \n  TO_CHAR(scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS') as schedule_time,\n  jr.project_name, \n  jr.job_name, \n  jr.status, \n  jl.owner,\n  now() - jr.start_time  as duration \nFROM \n  job_run jr \n  join job_labels jl on jr.job_name = jl.job_name \nWHERE \n  $__timeFilter(jr.scheduled_at) \n  and jr.project_name in ($project) \n  and jr.namespace_name in ($namespace) \n  and jr.status = 'running'\n  and jl.job_label in ($label)\norder by now() - jr.start_time desc \nlimit 10\n"
    }
   ]
  },
  {
   "title": "Group Level SLA breach percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\nSELECT \n        date(jr.scheduled_at) as time,\n        sum(case when jr.sla_alert = 'true' then 1 else 0 end ) as sla_miss_count,\n        sum(case when jr.sla_alert = 'false' then 1 else 0 end ) as sla_success_count, \n        count(*) as total_runs_count,\n        100 * sum(case when jr.sla_alert = 'true' then 1 else 0 end ) / count(*) failure_percentage\nFROM job_run jr\njoin job_labels jl\n  on\n  jr.project_name = jl.project_name \n  and\n  jr.job_name = jl.job_name\nWHERE $__timeFilter(jr.scheduled_at) \nand jr.project_name in ($project) \nand jr.namespace_name in ($namespace)  \nand jr.sla_definition > 0 \nand jl.job_label in ($label)\nGROUP BY jr.project_name,jr.namespace_name, date(jr.scheduled_at)"
    }
   ]
  },
  {
   "title": "daily success percentage trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\nSELECT  date(jr.scheduled_at),\n  sum(case when jr.status = 'failed' then 1 else 0 end ) failure_count,\n  sum(case when jr.status = 'success' then 1 else 0 end ) success_count,\n  count(*) as total_runs,\n  100 * sum(case when jr.status = 'success' then 1 else 0 end ) / count(*) success_percentage,\n  100 * sum(case when jr.status = 'failed' then 1 else 0 end ) / count(*) failure_percentage\nFROM job_run jr\njoin job_labels jl\non\n  jr.project_name = jl.project_name and\n  jr.job_name = jl.job_name\nWHERE \n  $__timeFilter(scheduled_at) \n  and jr.project_name in ($project) \n  and jr.namespace_name in ($namespace)\n  and jl.job_label in ($label)\n  and ( jr.status = 'failed' or jr.status = 'success' )\nGROUP BY date(jr.scheduled_at)"
    }
   ]
  },
  {
   "title": "Failed jobs in given time window",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\n\nSELECT\n  TO_CHAR(jr.scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS') as schedule_time,\n  jr.project_name , jr.namespace_name , jr.job_name \nFROM\n  job_run jr\njoin job_labels jl\non\n  jr.project_name = jl.project_name and\n  jr.job_name = jl.job_name\nWHERE\n  $__timeFilter(jr.scheduled_at) \n  and jr.project_name in ($project) \n  and jr.namespace_name in ($namespace)\n  and jl.job_label in ($label)\n  and status = 'failed' \n  order by jr.scheduled_at;"
    }
   ]
  },
  {
   "title": "job runs that breached SLA definitions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\nSELECT\n  TO_CHAR(jr.scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS') as schedule_time,\n  jr.project_name, jr.namespace_name, jr.job_name , jr.sla_definition\nFROM\n  job_run jr\njoin job_labels jl\non\n  jr.project_name = jl.project_name and\n  jr.job_name = jl.job_name\nWHERE\n  jr.sla_alert = 'true'\n  and jr.project_name in ($project) \n  and jr.namespace_name in ($namespace) \n  and $__timeFilter(jr.scheduled_at)\n  and jl.job_label in ($label)\n"
    }
   ]
  },
  {
   "title": "top 10 concluded jobs by longest duration",
   "type": "table",
   "description": "Adhere to  job_label",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 100 },
   "targets": [
    {
     "rawSql": "with job_labels as (\n    SELECT\n        job.name as job_name,\n        job.project_name as project_name,\n        job.owner as owner,\n        extracted_labels.value as job_label\n    FROM job, jsonb_each(job.labels) extracted_labels\n    where\n        project_name in ($project) and\n        namespace_name in ($namespace)\n)\n\n\nSELECT \n  TO_CHAR(jr.scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS') as schedule_time,\n  jr.project_name, \n  jr.job_name, \n  jr.status, \n  j.owner,\n  jr.end_time - jr.start_time as duration,\n  jl.job_label\nFROM \n  job_run jr \n  join job j on jr.project_name = j.project_name \n  and jr.job_name = j.name \n  join job_labels jl on j.name = jl.job_name\nWHERE \n  $__timeFilter(jr.scheduled_at) \n  and jr.project_name in ($project) \n  and jr.namespace_name in ($namespace) \n  and jr.status != 'running'\n  and jl.job_label in ($label)\norder by jr.end_time - jr.start_time desc \nlimit 10\n"
    }
   ]
  },
  {
   "title": "Longest wait times (Concluded Runs)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "rawSql": "with stuck_sensors as (\n  SELECT\n    TO_CHAR(jr.scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS') as schedule_time,\n    sr.name as sensor_name,\n    jr.job_name,\n    case\n      when max (sr.end_time) > now() then now() - max (sr.end_time)\n      else max(sr.end_time) - min (sr.start_time)\n    end duration,\n    --min(sr.start_time) as wait_start,\n    --case when max (sr.end_time) > now() then null else max (sr.end_time) end end_time,\n    count (*) as attemps,\n    case\n      when max (sr.end_time) > now() then 'Not Concluded'\n      else 'Finished'\n    end status\n  FROM\n    sensor_run sr\n    join job_run jr on sr.job_run_id = jr.id\n  WHERE\n    $__timeFilter(sr.start_time)\n    and sr.end_time < now()\n  group by\n    sr.name,\n    jr.job_name,\n    sr.job_run_id,\n    jr.scheduled_at\n  order by\n    max(sr.end_time) - min(sr.start_time) desc\n  limit\n    100\n)\nselect\n  s.*,\n  count(*) as downstream_count,\n  STRING_AGG(ju.job_name, ' , ') AS downstream\nfrom\n  stuck_sensors s\n  join job_upstream ju on ju.upstream_job_name = s.job_name\ngroup by\n  s.sensor_name,\n  s.job_name,\n  s.schedule_time,\n  s.duration,\n  s.attemps,\n  s.status\norder by   s.duration desc, downstream_count desc"
    }
   ]
  },
  {
   "title": "Longest wait times (Still ~Runing~) (Not Concluded)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "rawSql": "SELECT \n  sr.name as sensor_name,\n  jr.job_name,\n  TO_CHAR(jr.scheduled_at, 'DAY DD/mm/yyyy HH24:MI:SS') as schedule_time,\n  count (*) as attemps,\n  min(sr.start_time) as wait_start,\n  now() - min (sr.start_time) as running_since\nFROM \n  sensor_run sr join job_run jr on \n  sr.job_run_id = jr.id\nWHERE \n  $__timeFilter(sr.start_time) \n  and sr.end_time > now() \n\ngroup by sr.name,  jr.job_name, sr.job_run_id ,jr.scheduled_at\norder by count (*) desc\nlimit 200\n\n"
    }
   ]
  }
 ]
}