// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: gotocompany/optimus/core/v1beta1/backfill.proto

package optimus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackfillServiceClient is the client API for BackfillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackfillServiceClient interface {
	CreateBackfill(ctx context.Context, in *CreateBackfillRequest, opts ...grpc.CallOption) (*CreateBackfillResponse, error)
	BackfillPreview(ctx context.Context, in *BackfillPreviewRequest, opts ...grpc.CallOption) (*BackfillPreviewResponse, error)
	GetBackfill(ctx context.Context, in *GetBackfillRequest, opts ...grpc.CallOption) (*GetBackfillResponse, error)
	CancelBackfill(ctx context.Context, in *CancelBackfillRequest, opts ...grpc.CallOption) (*CancelBackfillResponse, error)
}

type backfillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackfillServiceClient(cc grpc.ClientConnInterface) BackfillServiceClient {
	return &backfillServiceClient{cc}
}

func (c *backfillServiceClient) CreateBackfill(ctx context.Context, in *CreateBackfillRequest, opts ...grpc.CallOption) (*CreateBackfillResponse, error) {
	out := new(CreateBackfillResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.BackfillService/CreateBackfill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backfillServiceClient) BackfillPreview(ctx context.Context, in *BackfillPreviewRequest, opts ...grpc.CallOption) (*BackfillPreviewResponse, error) {
	out := new(BackfillPreviewResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.BackfillService/BackfillPreview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backfillServiceClient) GetBackfill(ctx context.Context, in *GetBackfillRequest, opts ...grpc.CallOption) (*GetBackfillResponse, error) {
	out := new(GetBackfillResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.BackfillService/GetBackfill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backfillServiceClient) CancelBackfill(ctx context.Context, in *CancelBackfillRequest, opts ...grpc.CallOption) (*CancelBackfillResponse, error) {
	out := new(CancelBackfillResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.BackfillService/CancelBackfill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackfillServiceServer is the server API for BackfillService service.
// All implementations must embed UnimplementedBackfillServiceServer
// for forward compatibility
type BackfillServiceServer interface {
	CreateBackfill(context.Context, *CreateBackfillRequest) (*CreateBackfillResponse, error)
	BackfillPreview(context.Context, *BackfillPreviewRequest) (*BackfillPreviewResponse, error)
	GetBackfill(context.Context, *GetBackfillRequest) (*GetBackfillResponse, error)
	CancelBackfill(context.Context, *CancelBackfillRequest) (*CancelBackfillResponse, error)
	mustEmbedUnimplementedBackfillServiceServer()
}

// UnimplementedBackfillServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBackfillServiceServer struct {
}

func (UnimplementedBackfillServiceServer) CreateBackfill(context.Context, *CreateBackfillRequest) (*CreateBackfillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBackfill not implemented")
}
func (UnimplementedBackfillServiceServer) BackfillPreview(context.Context, *BackfillPreviewRequest) (*BackfillPreviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackfillPreview not implemented")
}
func (UnimplementedBackfillServiceServer) GetBackfill(context.Context, *GetBackfillRequest) (*GetBackfillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackfill not implemented")
}
func (UnimplementedBackfillServiceServer) CancelBackfill(context.Context, *CancelBackfillRequest) (*CancelBackfillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBackfill not implemented")
}
func (UnimplementedBackfillServiceServer) mustEmbedUnimplementedBackfillServiceServer() {}

// UnsafeBackfillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackfillServiceServer will
// result in compilation errors.
type UnsafeBackfillServiceServer interface {
	mustEmbedUnimplementedBackfillServiceServer()
}

func RegisterBackfillServiceServer(s grpc.ServiceRegistrar, srv BackfillServiceServer) {
	s.RegisterService(&BackfillService_ServiceDesc, srv)
}

func _BackfillService_CreateBackfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackfillServiceServer).CreateBackfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.BackfillService/CreateBackfill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackfillServiceServer).CreateBackfill(ctx, req.(*CreateBackfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackfillService_BackfillPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackfillPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackfillServiceServer).BackfillPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.BackfillService/BackfillPreview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackfillServiceServer).BackfillPreview(ctx, req.(*BackfillPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackfillService_GetBackfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackfillServiceServer).GetBackfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.BackfillService/GetBackfill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackfillServiceServer).GetBackfill(ctx, req.(*GetBackfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackfillService_CancelBackfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBackfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackfillServiceServer).CancelBackfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.BackfillService/CancelBackfill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackfillServiceServer).CancelBackfill(ctx, req.(*CancelBackfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackfillService_ServiceDesc is the grpc.ServiceDesc for BackfillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackfillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotocompany.optimus.core.v1beta1.BackfillService",
	HandlerType: (*BackfillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBackfill",
			Handler:    _BackfillService_CreateBackfill_Handler,
		},
		{
			MethodName: "BackfillPreview",
			Handler:    _BackfillService_BackfillPreview_Handler,
		},
		{
			MethodName: "GetBackfill",
			Handler:    _BackfillService_GetBackfill_Handler,
		},
		{
			MethodName: "CancelBackfill",
			Handler:    _BackfillService_CancelBackfill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gotocompany/optimus/core/v1beta1/backfill.proto",
}
