// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: gotocompany/optimus/core/v1beta1/completeness.proto

package optimus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CompletenessServiceClient is the client API for CompletenessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompletenessServiceClient interface {
	// CheckQueryCompleteness parses a SQL query, resolves the tables/views it reads from
	// (recursively through views down to base tables), and reports which of them are
	// managed by Optimus and whether their most relevant scheduled run has completed.
	CheckQueryCompleteness(ctx context.Context, in *CheckQueryCompletenessRequest, opts ...grpc.CallOption) (*CheckQueryCompletenessResponse, error)
}

type completenessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompletenessServiceClient(cc grpc.ClientConnInterface) CompletenessServiceClient {
	return &completenessServiceClient{cc}
}

func (c *completenessServiceClient) CheckQueryCompleteness(ctx context.Context, in *CheckQueryCompletenessRequest, opts ...grpc.CallOption) (*CheckQueryCompletenessResponse, error) {
	out := new(CheckQueryCompletenessResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.CompletenessService/CheckQueryCompleteness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompletenessServiceServer is the server API for CompletenessService service.
// All implementations must embed UnimplementedCompletenessServiceServer
// for forward compatibility
type CompletenessServiceServer interface {
	// CheckQueryCompleteness parses a SQL query, resolves the tables/views it reads from
	// (recursively through views down to base tables), and reports which of them are
	// managed by Optimus and whether their most relevant scheduled run has completed.
	CheckQueryCompleteness(context.Context, *CheckQueryCompletenessRequest) (*CheckQueryCompletenessResponse, error)
	mustEmbedUnimplementedCompletenessServiceServer()
}

// UnimplementedCompletenessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCompletenessServiceServer struct {
}

func (UnimplementedCompletenessServiceServer) CheckQueryCompleteness(context.Context, *CheckQueryCompletenessRequest) (*CheckQueryCompletenessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckQueryCompleteness not implemented")
}
func (UnimplementedCompletenessServiceServer) mustEmbedUnimplementedCompletenessServiceServer() {}

// UnsafeCompletenessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompletenessServiceServer will
// result in compilation errors.
type UnsafeCompletenessServiceServer interface {
	mustEmbedUnimplementedCompletenessServiceServer()
}

func RegisterCompletenessServiceServer(s grpc.ServiceRegistrar, srv CompletenessServiceServer) {
	s.RegisterService(&CompletenessService_ServiceDesc, srv)
}

func _CompletenessService_CheckQueryCompleteness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckQueryCompletenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletenessServiceServer).CheckQueryCompleteness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.CompletenessService/CheckQueryCompleteness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletenessServiceServer).CheckQueryCompleteness(ctx, req.(*CheckQueryCompletenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompletenessService_ServiceDesc is the grpc.ServiceDesc for CompletenessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompletenessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotocompany.optimus.core.v1beta1.CompletenessService",
	HandlerType: (*CompletenessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckQueryCompleteness",
			Handler:    _CompletenessService_CheckQueryCompleteness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gotocompany/optimus/core/v1beta1/completeness.proto",
}
