// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: gotocompany/optimus/core/v1beta1/replay.proto

package optimus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReplayServiceClient is the client API for ReplayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplayServiceClient interface {
	Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
	ReplayDryRun(ctx context.Context, in *ReplayDryRunRequest, opts ...grpc.CallOption) (*ReplayDryRunResponse, error)
	ListReplay(ctx context.Context, in *ListReplayRequest, opts ...grpc.CallOption) (*ListReplayResponse, error)
	GetReplay(ctx context.Context, in *GetReplayRequest, opts ...grpc.CallOption) (*GetReplayResponse, error)
	CancelReplay(ctx context.Context, in *CancelReplayRequest, opts ...grpc.CallOption) (*CancelReplayResponse, error)
	GetReplayDetails(ctx context.Context, in *GetReplayDetailsRequest, opts ...grpc.CallOption) (*GetReplayDetailsResponse, error)
}

type replayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplayServiceClient(cc grpc.ClientConnInterface) ReplayServiceClient {
	return &replayServiceClient{cc}
}

func (c *replayServiceClient) Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.ReplayService/Replay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replayServiceClient) ReplayDryRun(ctx context.Context, in *ReplayDryRunRequest, opts ...grpc.CallOption) (*ReplayDryRunResponse, error) {
	out := new(ReplayDryRunResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.ReplayService/ReplayDryRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replayServiceClient) ListReplay(ctx context.Context, in *ListReplayRequest, opts ...grpc.CallOption) (*ListReplayResponse, error) {
	out := new(ListReplayResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.ReplayService/ListReplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replayServiceClient) GetReplay(ctx context.Context, in *GetReplayRequest, opts ...grpc.CallOption) (*GetReplayResponse, error) {
	out := new(GetReplayResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.ReplayService/GetReplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replayServiceClient) CancelReplay(ctx context.Context, in *CancelReplayRequest, opts ...grpc.CallOption) (*CancelReplayResponse, error) {
	out := new(CancelReplayResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.ReplayService/CancelReplay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replayServiceClient) GetReplayDetails(ctx context.Context, in *GetReplayDetailsRequest, opts ...grpc.CallOption) (*GetReplayDetailsResponse, error) {
	out := new(GetReplayDetailsResponse)
	err := c.cc.Invoke(ctx, "/gotocompany.optimus.core.v1beta1.ReplayService/GetReplayDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplayServiceServer is the server API for ReplayService service.
// All implementations must embed UnimplementedReplayServiceServer
// for forward compatibility
type ReplayServiceServer interface {
	Replay(context.Context, *ReplayRequest) (*ReplayResponse, error)
	ReplayDryRun(context.Context, *ReplayDryRunRequest) (*ReplayDryRunResponse, error)
	ListReplay(context.Context, *ListReplayRequest) (*ListReplayResponse, error)
	GetReplay(context.Context, *GetReplayRequest) (*GetReplayResponse, error)
	CancelReplay(context.Context, *CancelReplayRequest) (*CancelReplayResponse, error)
	GetReplayDetails(context.Context, *GetReplayDetailsRequest) (*GetReplayDetailsResponse, error)
	mustEmbedUnimplementedReplayServiceServer()
}

// UnimplementedReplayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReplayServiceServer struct {
}

func (UnimplementedReplayServiceServer) Replay(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replay not implemented")
}
func (UnimplementedReplayServiceServer) ReplayDryRun(context.Context, *ReplayDryRunRequest) (*ReplayDryRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplayDryRun not implemented")
}
func (UnimplementedReplayServiceServer) ListReplay(context.Context, *ListReplayRequest) (*ListReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReplay not implemented")
}
func (UnimplementedReplayServiceServer) GetReplay(context.Context, *GetReplayRequest) (*GetReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplay not implemented")
}
func (UnimplementedReplayServiceServer) CancelReplay(context.Context, *CancelReplayRequest) (*CancelReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelReplay not implemented")
}
func (UnimplementedReplayServiceServer) GetReplayDetails(context.Context, *GetReplayDetailsRequest) (*GetReplayDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplayDetails not implemented")
}
func (UnimplementedReplayServiceServer) mustEmbedUnimplementedReplayServiceServer() {}

// UnsafeReplayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplayServiceServer will
// result in compilation errors.
type UnsafeReplayServiceServer interface {
	mustEmbedUnimplementedReplayServiceServer()
}

func RegisterReplayServiceServer(s grpc.ServiceRegistrar, srv ReplayServiceServer) {
	s.RegisterService(&ReplayService_ServiceDesc, srv)
}

func _ReplayService_Replay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayServiceServer).Replay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.ReplayService/Replay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayServiceServer).Replay(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplayService_ReplayDryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayDryRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayServiceServer).ReplayDryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.ReplayService/ReplayDryRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayServiceServer).ReplayDryRun(ctx, req.(*ReplayDryRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplayService_ListReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayServiceServer).ListReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.ReplayService/ListReplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayServiceServer).ListReplay(ctx, req.(*ListReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplayService_GetReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayServiceServer).GetReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.ReplayService/GetReplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayServiceServer).GetReplay(ctx, req.(*GetReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplayService_CancelReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayServiceServer).CancelReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.ReplayService/CancelReplay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayServiceServer).CancelReplay(ctx, req.(*CancelReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplayService_GetReplayDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplayDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayServiceServer).GetReplayDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gotocompany.optimus.core.v1beta1.ReplayService/GetReplayDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayServiceServer).GetReplayDetails(ctx, req.(*GetReplayDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplayService_ServiceDesc is the grpc.ServiceDesc for ReplayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gotocompany.optimus.core.v1beta1.ReplayService",
	HandlerType: (*ReplayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Replay",
			Handler:    _ReplayService_Replay_Handler,
		},
		{
			MethodName: "ReplayDryRun",
			Handler:    _ReplayService_ReplayDryRun_Handler,
		},
		{
			MethodName: "ListReplay",
			Handler:    _ReplayService_ListReplay_Handler,
		},
		{
			MethodName: "GetReplay",
			Handler:    _ReplayService_GetReplay_Handler,
		},
		{
			MethodName: "CancelReplay",
			Handler:    _ReplayService_CancelReplay_Handler,
		},
		{
			MethodName: "GetReplayDetails",
			Handler:    _ReplayService_GetReplayDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gotocompany/optimus/core/v1beta1/replay.proto",
}
