// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock_gitlab

import (
	mock "github.com/stretchr/testify/mock"
	gitlab "github.com/xanzy/go-gitlab"
)

// Commit is an autogenerated mock type for the Commit type
type Commit struct {
	mock.Mock
}

type Commit_Expecter struct {
	mock *mock.Mock
}

func (_m *Commit) EXPECT() *Commit_Expecter {
	return &Commit_Expecter{mock: &_m.Mock}
}

// ListCommits provides a mock function with given fields: pid, opt, options
func (_m *Commit) ListCommits(pid interface{}, opt *gitlab.ListCommitsOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.Commit, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListCommits")
	}

	var r0 []*gitlab.Commit
	var r1 *gitlab.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, *gitlab.ListCommitsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.Commit, *gitlab.Response, error)); ok {
		return rf(pid, opt, options...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, *gitlab.ListCommitsOptions, ...gitlab.RequestOptionFunc) []*gitlab.Commit); ok {
		r0 = rf(pid, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Commit)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, *gitlab.ListCommitsOptions, ...gitlab.RequestOptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, *gitlab.ListCommitsOptions, ...gitlab.RequestOptionFunc) error); ok {
		r2 = rf(pid, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Commit_ListCommits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCommits'
type Commit_ListCommits_Call struct {
	*mock.Call
}

// ListCommits is a helper method to define mock.On call
//   - pid interface{}
//   - opt *gitlab.ListCommitsOptions
//   - options ...gitlab.RequestOptionFunc
func (_e *Commit_Expecter) ListCommits(pid interface{}, opt interface{}, options ...interface{}) *Commit_ListCommits_Call {
	return &Commit_ListCommits_Call{Call: _e.mock.On("ListCommits",
		append([]interface{}{pid, opt}, options...)...)}
}

func (_c *Commit_ListCommits_Call) Run(run func(pid interface{}, opt *gitlab.ListCommitsOptions, options ...gitlab.RequestOptionFunc)) *Commit_ListCommits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]gitlab.RequestOptionFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(gitlab.RequestOptionFunc)
			}
		}
		run(args[0].(interface{}), args[1].(*gitlab.ListCommitsOptions), variadicArgs...)
	})
	return _c
}

func (_c *Commit_ListCommits_Call) Return(_a0 []*gitlab.Commit, _a1 *gitlab.Response, _a2 error) *Commit_ListCommits_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Commit_ListCommits_Call) RunAndReturn(run func(interface{}, *gitlab.ListCommitsOptions, ...gitlab.RequestOptionFunc) ([]*gitlab.Commit, *gitlab.Response, error)) *Commit_ListCommits_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommit creates a new instance of Commit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommit(t interface {
	mock.TestingT
	Cleanup(func())
}) *Commit {
	mock := &Commit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
