ALTER TABLE sync_status
ADD COLUMN IF NOT EXISTS last_sync_attempt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP '2000-01-01',
ADD COLUMN IF NOT EXISTS remarks JSONB,
ALTER COLUMN last_update_time DROP NOT NULL;
